definitions:
  route.StatsResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fuming.tsai@gogox.com
    name: Fu-Ming Tsai
  description: a sample for platform engineers to start with gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: gogovan-gin-sample-codes API
  version: 1.0.0
paths:
  /healthcheck:
    get:
      description: this return status after checking the system. However, it always
        returns "OK" at this moment.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.StatsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.StatsResponse'
      summary: health check for external monitoring system
      tags:
      - Monitoring
schemes:
- http
swagger: "2.0"
